version: '3'
services:
  db-about-api:
    image: postgres:12
    restart: always
    ports:
      - 5444:5432
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: about-api


  app:
    build: ./
    container_name: 'java-app'
    ports:
      - 8080:8080


